entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: <myemail>@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG
  filePath: ""

accessLog: {}
